/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as BuchungErfolgreichRouteImport } from './routes/buchung-erfolgreich'
import { Route as BuchungAbgebrochenRouteImport } from './routes/buchung-abgebrochen'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as ApiInternalPendingBookingsRouteImport } from './routes/api/internal/pending-bookings'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicAdminFinalizeBookingRouteImport } from './routes/api/public/admin/finalize-booking'

const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const BuchungErfolgreichRoute = BuchungErfolgreichRouteImport.update({
  id: '/buchung-erfolgreich',
  path: '/buchung-erfolgreich',
  getParentRoute: () => rootRouteImport,
} as any)
const BuchungAbgebrochenRoute = BuchungAbgebrochenRouteImport.update({
  id: '/buchung-abgebrochen',
  path: '/buchung-abgebrochen',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalPendingBookingsRoute =
  ApiInternalPendingBookingsRouteImport.update({
    id: '/api/internal/pending-bookings',
    path: '/api/internal/pending-bookings',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminFinalizeBookingRoute =
  ApiPublicAdminFinalizeBookingRouteImport.update({
    id: '/api/public/admin/finalize-booking',
    path: '/api/public/admin/finalize-booking',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/buchung-abgebrochen': typeof BuchungAbgebrochenRoute
  '/buchung-erfolgreich': typeof BuchungErfolgreichRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/api/internal/pending-bookings': typeof ApiInternalPendingBookingsRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/api/public/admin/finalize-booking': typeof ApiPublicAdminFinalizeBookingRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/buchung-abgebrochen': typeof BuchungAbgebrochenRoute
  '/buchung-erfolgreich': typeof BuchungErfolgreichRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/api/internal/pending-bookings': typeof ApiInternalPendingBookingsRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/api/public/admin/finalize-booking': typeof ApiPublicAdminFinalizeBookingRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/buchung-abgebrochen': typeof BuchungAbgebrochenRoute
  '/buchung-erfolgreich': typeof BuchungErfolgreichRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/api/internal/pending-bookings': typeof ApiInternalPendingBookingsRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/api/public/admin/finalize-booking': typeof ApiPublicAdminFinalizeBookingRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/buchung-abgebrochen'
    | '/buchung-erfolgreich'
    | '/datenschutz'
    | '/impressum'
    | '/api/internal/pending-bookings'
    | '/lovable/email/events'
    | '/api/public/admin/finalize-booking'
    | '/api/public/stripe/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/buchung-abgebrochen'
    | '/buchung-erfolgreich'
    | '/datenschutz'
    | '/impressum'
    | '/api/internal/pending-bookings'
    | '/lovable/email/events'
    | '/api/public/admin/finalize-booking'
    | '/api/public/stripe/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/buchung-abgebrochen'
    | '/buchung-erfolgreich'
    | '/datenschutz'
    | '/impressum'
    | '/api/internal/pending-bookings'
    | '/lovable/email/events'
    | '/api/public/admin/finalize-booking'
    | '/api/public/stripe/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  BuchungAbgebrochenRoute: typeof BuchungAbgebrochenRoute
  BuchungErfolgreichRoute: typeof BuchungErfolgreichRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  ApiInternalPendingBookingsRoute: typeof ApiInternalPendingBookingsRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  ApiPublicAdminFinalizeBookingRoute: typeof ApiPublicAdminFinalizeBookingRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buchung-erfolgreich': {
      id: '/buchung-erfolgreich'
      path: '/buchung-erfolgreich'
      fullPath: '/buchung-erfolgreich'
      preLoaderRoute: typeof BuchungErfolgreichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buchung-abgebrochen': {
      id: '/buchung-abgebrochen'
      path: '/buchung-abgebrochen'
      fullPath: '/buchung-abgebrochen'
      preLoaderRoute: typeof BuchungAbgebrochenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/pending-bookings': {
      id: '/api/internal/pending-bookings'
      path: '/api/internal/pending-bookings'
      fullPath: '/api/internal/pending-bookings'
      preLoaderRoute: typeof ApiInternalPendingBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/finalize-booking': {
      id: '/api/public/admin/finalize-booking'
      path: '/api/public/admin/finalize-booking'
      fullPath: '/api/public/admin/finalize-booking'
      preLoaderRoute: typeof ApiPublicAdminFinalizeBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  BuchungAbgebrochenRoute: BuchungAbgebrochenRoute,
  BuchungErfolgreichRoute: BuchungErfolgreichRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  ApiInternalPendingBookingsRoute: ApiInternalPendingBookingsRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  ApiPublicAdminFinalizeBookingRoute: ApiPublicAdminFinalizeBookingRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
